## Continuous Integration Workflow
name: Build and Deploy
on: [push, pull_request]

# Target Branch Job
jobs:
  Lint-Test:
    runs-on: ubuntu-latest
    steps:
      # Check Out Repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14

      # Install Node Dependencies
      - name: Installing NodeJS Dependencies
        run: npm install

      # Run ESLint
      - name: ESLint Check
        run: npx eslint . --config .eslintrc.js --ext .js,.ts

      # Run Prettier
      - name: Prettier Check
        run: npx prettier --check "src/**/*.ts"

      ## TODO: Add test scripts when Jest is configured

  Deploy:
    needs: [Lint-Test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
              - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku staging
