## Continuous Integration Workflow
name: Build and Deploy
on: [push, pull_request]

# Target Branch Job
jobs:
  # Lint-Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Check Out Repository
  #     - uses: actions/checkout@v1

  #     # Install Node.js
  #     - uses: actions/setup-node@v1.4.4
  #       with:
  #         node-version: 14

  #     # Install Node Dependencies
  #     - name: Installing NodeJS Dependencies
  #       run: npm install

  #     # Run ESLint
  #     - name: ESLint Check
  #       run: npx eslint . --config .eslintrc.js --ext .js,.ts

  #     # Run Prettier
  #     - name: Prettier Check
  #       run: npx prettier --check "src/**/*.ts"

  #     ## TODO: Add test scripts when Jest is configured

  Deploy:
    # needs: [Lint-Test]
    needs: []
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku Login Command
        run: |
          heroku login -i
          ${{ secrets.HEROKU_EMAIL }}
          ${{ secrets.HEROKU_API_KEY }}
      - name: Heroku Input Email
        run: |
          $HEROKU_EMAIL
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Heroku Input Password
        run: |
          $HEROKU_API_KEY
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Add Heroku remote
        run: heroku git:remote --app skylab-backend
      - name: Push to Heroku
        run: git push heroku staging:main
