## Continuous Integration Workflow
name: Build and Deploy
on:
  push:
    branches:
      - "staging"
  pull_request:
    branches:
      - "!staging"

# Target Branch Job
jobs:
  Lint-Test:
    runs-on: ubuntu-latest
    steps:
      # Check Out Repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14

      # Install Node Dependencies
      - name: Installing NodeJS Dependencies
        run: npm install

      # Run ESLint
      - name: ESLint Check
        run: npx eslint . --config .eslintrc.js --ext .js,.ts

      # Run Prettier
      - name: Prettier Check
        run: npx prettier --check "src/**/*.ts"

      ## TODO: Add test scripts when Jest is configured

  Deploy:
    needs: [Lint-Test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          remote_branch: "main"
          procfile: "web: ./node_modules/.bin/ts-node -r tsconfig-paths/register ./src"
